runtime: php81

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

env_variables:
  # Put production environment variables here.
  APP_DEBUG: false
  APP_ENV: development
  APP_KEY: base64:Hxj+LufVkGR06aaMqhYFjlvCF6k+ikpKkvLWHput5mc=
  APP_NAME: "RECYCRAFT"
  APP_URL: https://recycraft-backend-api-aysiqsilbq-et.a.run.app
  LOG_LEVEL: debug
  FILESYSTEM_DISK: gcs
  GOOGLE_CLOUD_KEY_FILE: ./credentials.json
  GOOGLE_CLOUD_PROJECT_ID: recycraft-c22-ps285
  GOOGLE_CLOUD_STORAGE_BUCKET: recycraft-c22-ps285.appspot.com
  GOOGLE_CLOUD_STORAGE_PATH_PREFIX: /uploads
  DB_CONNECTION: mysql
  DB_DATABASE: recycraft
  DB_USERNAME: recycraft_db
  DB_PASSWORD: recycraft123
  DB_SOCKET: '/cloudsql/recycraft-c22-ps285:asia-southeast2:recycraft-backend'

beta_settings:
  cloud_sql_instances: 'recycraft-c22-ps285:asia-southeast2:recycraft-backend'